---
defaultBaseImage: eu.gcr.io/stuttgart-things/sthings-workflow:1.30.1
builds:
  - id: machineshop
    dir: .
    main: main.go
    ldflags:
      - -s -w -X github.com/stuttgart-things/machineshop/cmd.version={{.Git.Tag}}
      - -s -w -X github.com/stuttgart-things/machineshop/cmd.date={{.Date}}
      - -s -w -X github.com/stuttgart-things/machineshop/cmd.commit={{.Git.ShortCommit}}
