---
defaultBaseImage: eu.gcr.io/stuttgart-things/sthings-workflow:1.30.1
ldflags:
  - -s -w -X github.com/stuttgart-things/machineshop/.version={{ .Version }} -X github.com/stuttgart-things/machineshop/.commit={{ .Commit }} -X github.com/stuttgart-things/machineshop/.date={{ .CommitDate }}
