---
name: Validate & Build clusterbook service
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'fix/**'
  pull_request:
    types: [opened, reopened]

jobs:
  Validate-Golang:
    name: Valdiate Golang Code
    uses: stuttgart-things/stuttgart-things/.github/workflows/call-golang-validation.yaml@workflow-golang-validation-123-1
    with:
      module-name: machineshop
      environment-name: k8s
      runs-on: ghr-machineshop-skyami-cicd
      golint-version: v1.61.0-alpine
      golang-version: 1.23.1
      accept-linterrors: true
      accept-failedtests: false
      timeout-minutes: 15m

  #Build-Image:
  #  name: Build Image
  #  uses: stuttgart-things/stuttgart-things/.github/workflows/call-ko-build.yaml@workflow-golang-validation-123-1
  #  with:
  #    environment-name: k8s
  #    runs-on: docker
