---
name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
  pull_request:
    types: [opened, reopened]

jobs:
  validate-golang:
    name: Valdiate Golang
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-golang-validation.yaml@feature/add-homerun-task-go #go-1.23.1
    with:
      module-name: kaeffken
      environment-name: k8s
      runs-on: ghr-machineshop-skyami-cicd
      golint-version: v1.61.0-alpine
      golang-version: "1.23.1"
      accept-linterrors: true
      accept-failedtests: false
    secrets: inherit  #pragma: allowlist secret
