---
name: Release-Golang
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
jobs:
  release-golang:
    name: Release Golang
    uses: stuttgart-things/stuttgart-things/.github/workflows/release-golang.yaml@main
    with:
      module-name: machineShop
      environment-name: k8s
      runs-on: ghr-machineshop-labda-test
      goreleaser-version: v1.23.0
      golang-version: "1.21.5"
    secrets: inherit
