---
name: Validate-Golang
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, reopened]

jobs:
  validate-golang:
    name: Valdiate Golang
    uses: stuttgart-things/stuttgart-things/.github/workflows/validate-golang.yaml@main
    with:
      module-name: machineshop
      environment-name: k8s
      runs-on: arc-runner-scale-set-machineshop
      golint-version: v1.55
      golang-version: "1.21.5"
      accept-linterrors: true
      accept-failedtests: false
